CREATE TABLE activitydata
(name VARCHAR(256) NOT NULL PRIMARY KEY,
address VARCHAR(256) NOT NULL,
description VARCHAR(256) NOT NULL,
age VARCHAR(256) NOT NULL,
fee VARCHAR(256) NOT NULL,
category VARCHAR(256) NOT NULL,
website VARCHAR(256) NOT NULL
);

